#!/bin/bash

# Check for releasenotes.txt
releaseNotesFile="releasenotes.txt"
if [ ! -f "$releaseNotesFile" ]; then
  touch "$releaseNotesFile"
  echo "Created releasenotes.txt"
fi

# Get current version from package.json
currentVersion=$(node -pe "require('./package.json').version")

# Get current date
currentDate=$(date '+%Y-%m-%d')

# Get commit messages
commitMessages=$(git log --pretty=format:"%h %s" @{u}..)

# Check if there are changes to push
if git diff --quiet --exit-code @{u}..; then
  echo "No changes to push. Exiting..."
  exit 1
fi

# There are changes to push, update releasenotes and version
echo "There are changes to push."

# Increase version in package.json
newVersion=$(npm version patch --no-git-tag-version)

# Update releasenotes.txt with new version and commit messages
echo "## $newVersion ($currentDate)" >> "$releaseNotesFile"
echo "$commitMessages" | sed -e 's/^/- /' >> "$releaseNotesFile"
echo "Updated $releaseNotesFile"

# Add package.json and releasenotes.txt changes to the commit
git add package.json "$releaseNotesFile"

# Perform any additional tasks here before the push
# For example:
# npm run build
git add .
git commit -m "Pre-push build"
echo "Pre-push tasks completed."

# Exit with success
exit 0
